name: "test action workflow"
on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '**.md'
env:
  branch: ${{github.ref}}

jobs:
  mytest1:
    # if: startsWith(github.ref, 'refs/heads/main/') || github.ref == 'refs/heads/main'
    if: contains(github.ref, 'maIN')
    name: test
    strategy:
      matrix:
          runtime: [ linux-x64, linux-arm64, linux-arm ]
          include:
          - runtime: linux-x64
            os: Ubuntu-24.04
  
          - runtime: linux-arm64
            os: Ubuntu-24.04
  
          - runtime: linux-arm
            os: Ubuntu-24.04
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: test
      run: |
        hostname -I;hostname;ip a;
