name: "test action workflow"
on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '**.md'
env:
  branch: ${{github.ref}}

jobs:
  build:
    strategy:
      matrix:
        runtime: [ linux-x64, linux-arm64, linux-arm, win-x64, win-arm64, osx-x64, osx-arm64 ]
        include:
        - runtime: linux-x64
          os: ubuntu-latest
          devScript: ./dev.sh

        - runtime: linux-arm64
          os: ubuntu-latest
          devScript: ./dev.sh

        - runtime: linux-arm
          os: ubuntu-latest
          devScript: ./dev.sh
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: test
      run: |
        hostname -I;hostname;ip a;
  
